/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HeathRouteImport } from './routes/heath'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangAboutRouteImport } from './routes/$lang/about'
import { Route as LangContactRouteImport } from './routes/$lang/contact'
import { Route as LangCookiesRouteImport } from './routes/$lang/cookies'
import { Route as LangFaqRouteImport } from './routes/$lang/faq'
import { Route as LangHeathRouteImport } from './routes/$lang/heath'
import { Route as LangJournalRouteImport } from './routes/$lang/journal'
import { Route as LangPartnerRouteImport } from './routes/$lang/partner'
import { Route as LangPrivacyRouteImport } from './routes/$lang/privacy'
import { Route as LangProductsRouteImport } from './routes/$lang/products'
import { Route as LangTermsRouteImport } from './routes/$lang/terms'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as PartnerIndexRouteImport } from './routes/partner.index'
import { Route as PartnerApplyRouteImport } from './routes/partner.apply'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as LangJournalIndexRouteImport } from './routes/$lang/journal.index'
import { Route as LangJournalSlugRouteImport } from './routes/$lang/journal.$slug'
import { Route as LangPartnerIndexRouteImport } from './routes/$lang/partner.index'
import { Route as LangPartnerApplyRouteImport } from './routes/$lang/partner.apply'
import { Route as LangProductsIndexRouteImport } from './routes/$lang/products.index'
import { Route as LangProductsSlugRouteImport } from './routes/$lang/products.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HeathRoute = HeathRouteImport.update({
  id: '/heath',
  path: '/heath',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const LangCookiesRoute = LangCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LangRoute,
} as any)
const LangFaqRoute = LangFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LangRoute,
} as any)
const LangHeathRoute = LangHeathRouteImport.update({
  id: '/heath',
  path: '/heath',
  getParentRoute: () => LangRoute,
} as any)
const LangJournalRoute = LangJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => LangRoute,
} as any)
const LangPartnerRoute = LangPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => LangRoute,
} as any)
const LangPrivacyRoute = LangPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LangRoute,
} as any)
const LangProductsRoute = LangProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => LangRoute,
} as any)
const LangTermsRoute = LangTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LangRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JournalRoute,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerApplyRoute = PartnerApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => PartnerRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const LangJournalIndexRoute = LangJournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangJournalRoute,
} as any)
const LangJournalSlugRoute = LangJournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LangJournalRoute,
} as any)
const LangPartnerIndexRoute = LangPartnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangPartnerRoute,
} as any)
const LangPartnerApplyRoute = LangPartnerApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => LangPartnerRoute,
} as any)
const LangProductsIndexRoute = LangProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangProductsRoute,
} as any)
const LangProductsSlugRoute = LangProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LangProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/heath': typeof HeathRoute
  '/journal': typeof JournalRouteWithChildren
  '/partner': typeof PartnerRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/cookies': typeof LangCookiesRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/heath': typeof LangHeathRoute
  '/$lang/journal': typeof LangJournalRouteWithChildren
  '/$lang/partner': typeof LangPartnerRouteWithChildren
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/products': typeof LangProductsRouteWithChildren
  '/$lang/terms': typeof LangTermsRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/partner/apply': typeof PartnerApplyRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/$lang/': typeof LangIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/$lang/journal/$slug': typeof LangJournalSlugRoute
  '/$lang/partner/apply': typeof LangPartnerApplyRoute
  '/$lang/products/$slug': typeof LangProductsSlugRoute
  '/$lang/journal/': typeof LangJournalIndexRoute
  '/$lang/partner/': typeof LangPartnerIndexRoute
  '/$lang/products/': typeof LangProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/heath': typeof HeathRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/cookies': typeof LangCookiesRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/heath': typeof LangHeathRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/terms': typeof LangTermsRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/partner/apply': typeof PartnerApplyRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/$lang': typeof LangIndexRoute
  '/journal': typeof JournalIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/products': typeof ProductsIndexRoute
  '/$lang/journal/$slug': typeof LangJournalSlugRoute
  '/$lang/partner/apply': typeof LangPartnerApplyRoute
  '/$lang/products/$slug': typeof LangProductsSlugRoute
  '/$lang/journal': typeof LangJournalIndexRoute
  '/$lang/partner': typeof LangPartnerIndexRoute
  '/$lang/products': typeof LangProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/heath': typeof HeathRoute
  '/journal': typeof JournalRouteWithChildren
  '/partner': typeof PartnerRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/cookies': typeof LangCookiesRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/heath': typeof LangHeathRoute
  '/$lang/journal': typeof LangJournalRouteWithChildren
  '/$lang/partner': typeof LangPartnerRouteWithChildren
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/products': typeof LangProductsRouteWithChildren
  '/$lang/terms': typeof LangTermsRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/partner/apply': typeof PartnerApplyRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/$lang/': typeof LangIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/$lang/journal/$slug': typeof LangJournalSlugRoute
  '/$lang/partner/apply': typeof LangPartnerApplyRoute
  '/$lang/products/$slug': typeof LangProductsSlugRoute
  '/$lang/journal/': typeof LangJournalIndexRoute
  '/$lang/partner/': typeof LangPartnerIndexRoute
  '/$lang/products/': typeof LangProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/heath'
    | '/journal'
    | '/partner'
    | '/privacy'
    | '/products'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/cookies'
    | '/$lang/faq'
    | '/$lang/heath'
    | '/$lang/journal'
    | '/$lang/partner'
    | '/$lang/privacy'
    | '/$lang/products'
    | '/$lang/terms'
    | '/journal/$slug'
    | '/partner/apply'
    | '/products/$slug'
    | '/$lang/'
    | '/journal/'
    | '/partner/'
    | '/products/'
    | '/$lang/journal/$slug'
    | '/$lang/partner/apply'
    | '/$lang/products/$slug'
    | '/$lang/journal/'
    | '/$lang/partner/'
    | '/$lang/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/heath'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/cookies'
    | '/$lang/faq'
    | '/$lang/heath'
    | '/$lang/privacy'
    | '/$lang/terms'
    | '/journal/$slug'
    | '/partner/apply'
    | '/products/$slug'
    | '/$lang'
    | '/journal'
    | '/partner'
    | '/products'
    | '/$lang/journal/$slug'
    | '/$lang/partner/apply'
    | '/$lang/products/$slug'
    | '/$lang/journal'
    | '/$lang/partner'
    | '/$lang/products'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/heath'
    | '/journal'
    | '/partner'
    | '/privacy'
    | '/products'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/cookies'
    | '/$lang/faq'
    | '/$lang/heath'
    | '/$lang/journal'
    | '/$lang/partner'
    | '/$lang/privacy'
    | '/$lang/products'
    | '/$lang/terms'
    | '/journal/$slug'
    | '/partner/apply'
    | '/products/$slug'
    | '/$lang/'
    | '/journal/'
    | '/partner/'
    | '/products/'
    | '/$lang/journal/$slug'
    | '/$lang/partner/apply'
    | '/$lang/products/$slug'
    | '/$lang/journal/'
    | '/$lang/partner/'
    | '/$lang/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  HeathRoute: typeof HeathRoute
  JournalRoute: typeof JournalRouteWithChildren
  PartnerRoute: typeof PartnerRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heath': {
      id: '/heath'
      path: '/heath'
      fullPath: '/heath'
      preLoaderRoute: typeof HeathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/cookies': {
      id: '/$lang/cookies'
      path: '/cookies'
      fullPath: '/$lang/cookies'
      preLoaderRoute: typeof LangCookiesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/faq': {
      id: '/$lang/faq'
      path: '/faq'
      fullPath: '/$lang/faq'
      preLoaderRoute: typeof LangFaqRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/heath': {
      id: '/$lang/heath'
      path: '/heath'
      fullPath: '/$lang/heath'
      preLoaderRoute: typeof LangHeathRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/journal': {
      id: '/$lang/journal'
      path: '/journal'
      fullPath: '/$lang/journal'
      preLoaderRoute: typeof LangJournalRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/partner': {
      id: '/$lang/partner'
      path: '/partner'
      fullPath: '/$lang/partner'
      preLoaderRoute: typeof LangPartnerRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/privacy': {
      id: '/$lang/privacy'
      path: '/privacy'
      fullPath: '/$lang/privacy'
      preLoaderRoute: typeof LangPrivacyRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/products': {
      id: '/$lang/products'
      path: '/products'
      fullPath: '/$lang/products'
      preLoaderRoute: typeof LangProductsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/terms': {
      id: '/$lang/terms'
      path: '/terms'
      fullPath: '/$lang/terms'
      preLoaderRoute: typeof LangTermsRouteImport
      parentRoute: typeof LangRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/partner/': {
      id: '/partner/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/apply': {
      id: '/partner/apply'
      path: '/apply'
      fullPath: '/partner/apply'
      preLoaderRoute: typeof PartnerApplyRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/$lang/journal/': {
      id: '/$lang/journal/'
      path: '/'
      fullPath: '/$lang/journal/'
      preLoaderRoute: typeof LangJournalIndexRouteImport
      parentRoute: typeof LangJournalRoute
    }
    '/$lang/journal/$slug': {
      id: '/$lang/journal/$slug'
      path: '/$slug'
      fullPath: '/$lang/journal/$slug'
      preLoaderRoute: typeof LangJournalSlugRouteImport
      parentRoute: typeof LangJournalRoute
    }
    '/$lang/partner/': {
      id: '/$lang/partner/'
      path: '/'
      fullPath: '/$lang/partner/'
      preLoaderRoute: typeof LangPartnerIndexRouteImport
      parentRoute: typeof LangPartnerRoute
    }
    '/$lang/partner/apply': {
      id: '/$lang/partner/apply'
      path: '/apply'
      fullPath: '/$lang/partner/apply'
      preLoaderRoute: typeof LangPartnerApplyRouteImport
      parentRoute: typeof LangPartnerRoute
    }
    '/$lang/products/': {
      id: '/$lang/products/'
      path: '/'
      fullPath: '/$lang/products/'
      preLoaderRoute: typeof LangProductsIndexRouteImport
      parentRoute: typeof LangProductsRoute
    }
    '/$lang/products/$slug': {
      id: '/$lang/products/$slug'
      path: '/$slug'
      fullPath: '/$lang/products/$slug'
      preLoaderRoute: typeof LangProductsSlugRouteImport
      parentRoute: typeof LangProductsRoute
    }
  }
}

interface LangJournalRouteChildren {
  LangJournalSlugRoute: typeof LangJournalSlugRoute
  LangJournalIndexRoute: typeof LangJournalIndexRoute
}

const LangJournalRouteChildren: LangJournalRouteChildren = {
  LangJournalSlugRoute: LangJournalSlugRoute,
  LangJournalIndexRoute: LangJournalIndexRoute,
}

const LangJournalRouteWithChildren = LangJournalRoute._addFileChildren(
  LangJournalRouteChildren,
)

interface LangPartnerRouteChildren {
  LangPartnerApplyRoute: typeof LangPartnerApplyRoute
  LangPartnerIndexRoute: typeof LangPartnerIndexRoute
}

const LangPartnerRouteChildren: LangPartnerRouteChildren = {
  LangPartnerApplyRoute: LangPartnerApplyRoute,
  LangPartnerIndexRoute: LangPartnerIndexRoute,
}

const LangPartnerRouteWithChildren = LangPartnerRoute._addFileChildren(
  LangPartnerRouteChildren,
)

interface LangProductsRouteChildren {
  LangProductsSlugRoute: typeof LangProductsSlugRoute
  LangProductsIndexRoute: typeof LangProductsIndexRoute
}

const LangProductsRouteChildren: LangProductsRouteChildren = {
  LangProductsSlugRoute: LangProductsSlugRoute,
  LangProductsIndexRoute: LangProductsIndexRoute,
}

const LangProductsRouteWithChildren = LangProductsRoute._addFileChildren(
  LangProductsRouteChildren,
)

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangContactRoute: typeof LangContactRoute
  LangCookiesRoute: typeof LangCookiesRoute
  LangFaqRoute: typeof LangFaqRoute
  LangHeathRoute: typeof LangHeathRoute
  LangJournalRoute: typeof LangJournalRouteWithChildren
  LangPartnerRoute: typeof LangPartnerRouteWithChildren
  LangPrivacyRoute: typeof LangPrivacyRoute
  LangProductsRoute: typeof LangProductsRouteWithChildren
  LangTermsRoute: typeof LangTermsRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangContactRoute: LangContactRoute,
  LangCookiesRoute: LangCookiesRoute,
  LangFaqRoute: LangFaqRoute,
  LangHeathRoute: LangHeathRoute,
  LangJournalRoute: LangJournalRouteWithChildren,
  LangPartnerRoute: LangPartnerRouteWithChildren,
  LangPrivacyRoute: LangPrivacyRoute,
  LangProductsRoute: LangProductsRouteWithChildren,
  LangTermsRoute: LangTermsRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface PartnerRouteChildren {
  PartnerApplyRoute: typeof PartnerApplyRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
}

const PartnerRouteChildren: PartnerRouteChildren = {
  PartnerApplyRoute: PartnerApplyRoute,
  PartnerIndexRoute: PartnerIndexRoute,
}

const PartnerRouteWithChildren =
  PartnerRoute._addFileChildren(PartnerRouteChildren)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  HeathRoute: HeathRoute,
  JournalRoute: JournalRouteWithChildren,
  PartnerRoute: PartnerRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
